apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  selector:
    app: task-manager
  ports:
    - protocol: TCP
      port: 80      # Puerto del servicio
      targetPort: 8080  # Puerto en el contenedor
  type: NodePort
